// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  return {
    routes: {"1":{"path":"/","id":"1"}},
    routeComponents: {
'1': React.lazy(() => import(/* webpackChunkName: "p__HelloWorld" */'@/pages/HelloWorld.js')),
},
  };
}
